apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: gcr.io/mordeczki-project/migration:0.0.1
        env:
          - name: DB_PASSWORD
            value: admin123
          - name: DB_USERNAME
            value: postgresadmin
          - name: DB_URL
            value: jdbc:postgresql://postgres.default.svc.cluster.local:5432/postgresdb
          - name: DB_DRIVER
            value: org.postgresql.Driver
      restartPolicy: Never
  backoffLimit: 4



