version: '3'
services:

  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: mordeczki
    ports:
      - 5432:5432
      
      
  migrations:
    image: mordeczki-migration:0.0.1-SNAPSHOT
#  build: 
#      context: .
#      dockerfile: dockerfile-migration
    links:
    - postgres
    depends_on:
    - postgres
    environment:
      DB_PASSWORD: secret
      DB_USERNAME: postgres
      DB_URL: jdbc:postgresql://postgres:5432/mordeczki
      DB_DRIVER: org.postgresql.Driver

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.9
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  
  kafka:
    image: confluentinc/cp-kafka:6.2.6
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth-api:
    image: mordeczki-auth-api:0.0.1-SNAPSHOT
    ports:
    - "8080:8080"
    links:
    - migrations
    depends_on:
    - migrations
    - kafka
    environment:
      DB_PASSWORD: secret
      DB_USERNAME: postgres
      DB_URL: jdbc:postgresql://postgres:5432/mordeczki
      DB_DRIVER: org.postgresql.Driver
      KAFKA_ADDRESS: kafka:29092

