version: '3'
services:

  postgres:
    image: postgres:11.1
#    volumes:
#      - ./src/test/resources/db-schema.sql
#    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: mordeczki

  migrations:
    image: mordeczki-migration:0.0.1-SNAPSHOT
    links:
    - postgres
    depends_on:
    - postgres
    environment:
      DB_PASSWORD: secret
      DB_USERNAME: postgres
      DB_URL: jdbc:postgresql://postgres:5432/mordeczki
      DB_DRIVER: org.postgresql.Driver


