version: '3'
services:

  postgres:
    image: postgres:11.1
#    volumes:
#      - ./src/test/resources/db-schema.sql
#    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: mordeczki

  migrations:
    build: 
      context: .
      dockerfile: dockerfile-migration
    links:
    - postgres
    depends_on:
    - postgres
    environment:
      DB_PASSWORD: secret
      DB_USERNAME: postgres
      DB_URL: jdbc:postgresql://postgres:5432/mordeczki
      DB_DRIVER: org.postgresql.Driver

  auth-web:
    build: 
      context: .
      dockerfile: dockerfile-auth-web
    ports:
    - "8080:8080"
    links:
    - migrations
    depends_on:
    - migrations
    environment:
      DB_PASSWORD: secret
      DB_USERNAME: postgres
      DB_URL: jdbc:postgresql://postgres:5432/mordeczki
      DB_DRIVER: org.postgresql.Driver

