FROM maven:3.8-openjdk-16-slim

#RUN addgroup -S spring && adduser -S spring -G spring

#USER spring:spring


ADD . mordeczki
WORKDIR /mordeczki

RUN mvn clean install -DskipTests

CMD ["java", "-jar", "migration/target/mordeczki-migration.jar"]


