version: '3'
services:

  postgres:
    image: postgres:11.1
    volumes:
      - ./src/test/resources/db-schema.sql.sql
#    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: search

  search:
    build: .
    ports:
    - "8080:8080"
    links:
    - postgres
    depends_on:
    - postgres
    environment:
      DB_PASSWORD: secret
      DB_USERNAME: postgres
      DB_URL: postgres
